### Numpy array and Basis 
    
by chai aur code

In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5]) 
print("1D array : " , arr_1d) 


arr_2d = np.array([[1, 2, 3] , [4, 5, 6]]) 
print("2D array : " , arr_2d) 

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


In [ ]:
# In VS Code Jupyter Notebooks, the shortcut to add a markdown cell below is:
# Press 'B' to add a new cell below, then press 'M' to convert it to Markdown.
# (Make sure you are in command mode by pressing 'Esc' first.)

In [ ]:
# In VS Code Jupyter Notebooks, the shortcut to add a code cell below is:
# Press 'B' to add a new cell below.
# (Make sure you are in command mode by pressing 'Esc' first.)

### List v/s Numpy array


In [6]:
py_list = [1, 2, 3]
print("Python List multiplication : " , py_list * 2) 


np_array = np.array([1, 2, 3]) #element vise multiplication 
print("Python array multiplication : " , np_array * 2) 


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : " , time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : " , time.time() - start)

Python List multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

 List operation time :  0.05279350280761719

 Numpy operation time :  0.004999637603759766


### Creating array from scratch


In [ ]:
zeros = np.zeros((3, 4)) 
print("\nZeroes array : \n" , zeros)


ones = np.ones((2, 4)) 
print("\nOnes array : \n" , ones)


full = np.full((2, 2), 7) 
print("\nFull array : \n" , full)


random = np.random.random((2, 3))
print("\nRandom array : \n" , random)


sequence = np.arange(0, 10, 2) # (start , stop , jump) but stop and stop-1 is not included 1
print("\nSequence array : \n" , sequence)



Zeroes array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full array : 
 [[7 7]
 [7 7]]

Random array : 
 [[0.95942937 0.99750576 0.81760456]
 [0.85856548 0.01768342 0.21098985]]

Sequence array : 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [19]:
vector = np.array([1, 2, 3, 4, 5])
print("\n Vector : " , vector)


matrix = np.array([[1, 2, 3] ,
                   [4, 5, 6]])
print("Matrix : " , matrix)


tensor = np.array([[[1, 2] , [3, 4]],
                   [[5, 6] , [7, 8]]]) 
print("Tensor : " , tensor)


 Vector :  [1 2 3 4 5]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties 

In [38]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape of array : " , arr.shape) 
print("Dimension of array : " , arr.ndim) 
print("Size of array : " , arr.size) 
print("Data Type of array : " , arr.dtype) # Datatypes should be same in numpy array


Shape of array :  (2, 3)
Dimension of array :  2
Size of array :  6
Data Type of array :  int64


### Array Reshaping

In [7]:
import numpy as np 


In [15]:
arr = np.arange(12)
print("\nOriginal array : \n" , arr) 


reshaped = arr.reshape((3, 4)) # to change the shape of an array without modifying the original array. It returns a new view (when possible) of the array with the specified shape.
print("\nReshaped array : \n" , reshaped)


resize = np.resize(arr, (4, 4)) #to change the shape (dimensions) of an array, either in-place or by returning a new one.
print("\nResized array : \n", resize)


flattened = resize.flatten() #to flat the multi dimensional array
print("\nFlattened array : \n" , flattened)


raveled = resize.ravel() #returns view, instead of copy
print("\nRaveled array : \n" , raveled)


transpose = reshaped.T #Transpose the matrix
print("\nTransposed array : \n" , transpose)


Original array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Resized array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]

Flattened array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3]

Raveled array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3]

Transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
