## Numpy array operations 

In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n Basic Slicing : " , arr[2 : 7])
print("\n Step Slicing : " , arr[2 : 8 : 2])
print("\n Negative Indexing : " , arr[-3])


 Basic Slicing :  [3 4 5 6 7]

 Step Slicing :  [3 5 7]

 Negative Indexing :  8


## 2D array 


In [8]:
arr_2d = np.array([[1, 2, 3] , 
                   [4, 5, 6] , 
                   [7, 8, 9]])
print("\n Specific Element : " , arr_2d[1, 2])
print("\n Entire row : " , arr_2d[1])
print("\n Entire Column : " , arr_2d[:, 2])


 Specific Element :  6

 Entire row :  [4 5 6]

 Entire Column :  [3 6 9]


## Sorting

In [14]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 12, 0])
print("\n Sorted array : " , np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [10, 2], [2, 3]])
print("\n Sorted 2D array by column (top-to-bottom) : \n" , np.sort(arr_2d_unsorted , axis=0)) # axis=0 -> top-to-bottom sorting
print("\n Sorted 2D array by row (left-to-right) : \n" , np.sort(arr_2d_unsorted , axis=1)) # axis=1 ->  left-to-right sorting


 Sorted array :  [ 0  1  1  2  3  4  5  9 12]

 Sorted 2D array by column (top-to-bottom) : 
 [[ 2  1]
 [ 3  2]
 [10  3]]

 Sorted 2D array by row (left-to-right) : 
 [[ 1  3]
 [ 2 10]
 [ 2  3]]


## Filtering array

In [ ]:
numbers = np.arange(11)

# filtering even numbers 
even_numbers = numbers[numbers % 2 == 0] 
print("\n Filtered even numbers from array is " , even_numbers)

# filtring odd numbers 
odd_numbers = numbers[numbers % 2 != 0] 
print("\n Filtered odd numbers from array is : " , odd_numbers)


 Filtered even numbers from array is  [ 0  2  4  6  8 10]

 Filtered odd numbers from array is :  [1 3 5 7 9]


## Filter with Mask 

In [ ]:
# filtering numbers greater tha ffrom the array 
mask = numbers > 5 
print("\n Numbers greater than 5 : " , numbers[mask])


 Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy indexing v/s np.where()

In [27]:
nums = np.array([0, 10, 12, 35, 64, 5, 61, 70, 98, 11, 10])

# printing indices but indices taken altready in a variable
indices = [0, 4, 7]
print("\n Indices elements are : " , nums[indices])


# np.where()
where_result = np.where(nums > 50)
print("\n Indices of nums which are greater than 50 : " , where_result) # where_result will store the index of numbers which are greater than 50
print("\n NP Where elements : " , nums[where_result])




 Indices elements are :  [ 0 64 70]

 Indices of nums which are greater than 50 :  (array([4, 6, 7, 8]),)

 NP Where elements :  [64 61 70 98]


In [ ]:
conditional_array1 = np.where(nums > 45 , nums*2 , nums) # in this nums which are greater than 45 they were multiplis by 2, and we have to pass the array also in arguments with more than one conditions
print("\n Conditional array : " , conditional_array1)

# example dry run of above code 
'''
if(nums > 45) {
    return nums*2
} else {
    return nums
}
'''

# if nums is greater than 45 then it will print true otherise false
conditional_array2 = np.where(nums > 45 , "True" , "False")
print("\n Conditional array (True/False) : " , conditional_array2)


 Conditional array :  [  0  10  12  35 128   5 122 140 196  11  10]

 Conditional array (True/False) :  ['False' 'False' 'False' 'False' 'True' 'False' 'True' 'True' 'True'
 'False' 'False']


## Merging array 


In [40]:
arr1 = np.array([1, 4, 6, 8])
arr2 = np.array([7, 10, 11, 15])

# merging arr1 & arr2
combined = np.concatenate((arr1 , arr2))
print("\n Combination of arr1 & arr2 is : " , combined)


 Combination of arr1 & arr2 is :  [ 1  4  6  8  7 10 11 15]


## Array Compatibility 

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# checking the shape of two array is same or not 
print("\n Compatibility shape of two array : " , arr1.shape == arr2.shape)

# checking multiple arrays at a time 
print("\n Compatibility shape of three array : " , arr1.shape == arr2.shape == arr3.shape)


 Compatibility shape :  True

 Compatibility shape :  True


## Adding new Row in 2D array

In [ ]:
# 2D array 
original_2d_array1 = np.array([[1, 2] ,
                             [3, 4]])
# new row for adding 
new_row = np.array([[5, 6]])

# with new row 
with_new_row = np.vstack((original_2d_array1 , new_row)) # here vstack() will add the new row(left-to-right) in 2D array

print("\n Original 2D array : \n" , original_2d_array1)
print("\n New row : \n" , new_row)
print("\n New array after adding new row in 2D array : \n" , with_new_row)



 Original 2D array : 
 [[1 2]
 [3 4]]

 New 1D array : 
 [[5 6]]

 New array after adding new row in 2D array : 
 [[1 2]
 [3 4]
 [5 6]]


## Adding new Column in 2D array 

In [ ]:
# 2D array
original_2d_array2 = np.array([[1, 3] , 
                              [2, 4]])

# new column 
new_column = np.array([[5] , [6]])

# with new column 
with_new_column = np.hstack((original_2d_array2 , new_column)) # hstack() will add new column(top-to-bottom) in 2D array

print("\n Original 2D array : \n" , original_2d_array2)
print("\n New column : \n" , new_column)
print("\n New array after adding new column in 2D array : \n" , with_new_column)


 Original 2D array : 
 [[1 3]
 [2 4]]

 New column : 
 [[5]
 [6]]

 New array after adding new column in 2D array : 
 [[1 3 5]
 [2 4 6]]


## Deletion in 1D array

In [52]:
# new array
new_arr = np.array([1, 2, 3, 4, 5, 6, 7])

deleted = np.delete(new_arr , 3) 
print("\n Array after deletion : " , deleted)


 Array after deletion :  [1 2 3 5 6 7]
