## Storing image in Matrix  

In [2]:
import numpy as np 
import matplotlib.pyplot as plt

### Creating array (saved in memory)

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.random.rand(3, 3)
arr3 = np.zeros((4, 4))

### Saving in flat files 

In [7]:
np.save('arr1.npy' , arr1)
np.save('arr2.npy' , arr2)
np.save('arr3.npy' , arr3)

### Loading above array 

In [11]:
# loading array 1 
loading_arr1 = np.load('arr1.npy')
print("\nLoaded arr1 : \n" , loading_arr1)

# loading array 2
loading_arr2 = np.load('arr2.npy')
print("\nLoaded arr2 : \n" , loading_arr2)

# loading array 3 
loading_arr3 = np.load('arr3.npy')
print("\nLoaded arr3 : \n" , loading_arr3)


Loaded arr1 : 
 [[1 2 3]
 [4 5 6]]

Loaded arr2 : 
 [[0.01136614 0.60309767 0.77219519]
 [0.86018623 0.40123322 0.13424745]
 [0.67982553 0.09803548 0.7647753 ]]

Loaded arr3 : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
